"""Add order tables

Revision ID: 328997d3e8c8
Revises: 
Create Date: 2025-10-29 17:25:11.885264

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '328997d3e8c8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('email', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('phone', sa.String(length=15), nullable=False))
        batch_op.add_column(sa.Column('address', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('landmark', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('city', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('pincode', sa.String(length=10), nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_id')
        batch_op.drop_column('timestamp')

    with op.batch_alter_table('order_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_name', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('subtotal', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('image', sa.String(length=255), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_item', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'product', ['product_id'], ['id'])
        batch_op.drop_column('image')
        batch_op.drop_column('subtotal')
        batch_op.drop_column('product_name')

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), nullable=False))
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])
        batch_op.drop_column('created_at')
        batch_op.drop_column('pincode')
        batch_op.drop_column('city')
        batch_op.drop_column('landmark')
        batch_op.drop_column('address')
        batch_op.drop_column('phone')
        batch_op.drop_column('email')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
